import type { FoodItem, MockUser, Order } from "@/lib/types";

export const foodItems: FoodItem[] = [
  {
    id: "masala-wrap",
    name: "Masala Paneer Wrap",
    description: "Whole wheat wrap with paneer tikka, mint yogurt, and crisp campus greens.",
    price: 129,
    rating: 4.7,
    category: "Veg",
    vendor: "North Gate Kitchen",
    availability: "Available",
    popularity: 94,
    prepTime: "15 min",
    image: "/food/paneer-wrap.svg",
    accent: "from-orange-100 to-amber-50",
  },
  {
    id: "hostel-thali",
    name: "Hostel Comfort Thali",
    description: "Dal, jeera rice, seasonal sabzi, soft rotis, and a sweet bite for late lectures.",
    price: 149,
    rating: 4.8,
    category: "Veg",
    vendor: "Mess Collective",
    availability: "Available",
    popularity: 98,
    prepTime: "18 min",
    image: "/food/thali.svg",
    accent: "from-stone-100 to-orange-50",
  },
  {
    id: "peri-peri-bowl",
    name: "Peri Peri Chicken Bowl",
    description: "Spiced chicken, herbed rice, roasted veggies, and creamy garlic drizzle.",
    price: 189,
    rating: 4.6,
    category: "Non-Veg",
    vendor: "Central Grill Lab",
    availability: "Available",
    popularity: 90,
    prepTime: "20 min",
    image: "/food/chicken-bowl.svg",
    accent: "from-red-100 to-orange-50",
  },
  {
    id: "study-samosa",
    name: "Study Break Samosa Box",
    description: "Four crisp samosas with tamarind dip for group assignments and chai breaks.",
    price: 89,
    rating: 4.5,
    category: "Snacks",
    vendor: "Library Lane Bites",
    availability: "Limited",
    popularity: 88,
    prepTime: "10 min",
    image: "/food/samosa-box.svg",
    accent: "from-yellow-100 to-orange-50",
  },
  {
    id: "cold-coffee",
    name: "Cold Coffee Float",
    description: "Campus cafe style cold coffee with vanilla foam and a gentle cocoa finish.",
    price: 99,
    rating: 4.4,
    category: "Drinks",
    vendor: "Brew Block",
    availability: "Available",
    popularity: 82,
    prepTime: "7 min",
    image: "/food/cold-coffee.svg",
    accent: "from-amber-100 to-stone-100",
  },
  {
    id: "noodle-cup",
    name: "Midnight Noodle Cup",
    description: "Wok tossed noodles with spring onion crunch and a peppery campus-style sauce.",
    price: 119,
    rating: 4.3,
    category: "Snacks",
    vendor: "Night Canteen",
    availability: "Available",
    popularity: 85,
    prepTime: "12 min",
    image: "/food/noodle-cup.svg",
    accent: "from-lime-100 to-amber-50",
  },
  {
    id: "mango-lassi",
    name: "Mango Lassi Cooler",
    description: "Thick mango lassi chilled for hot afternoons between seminars and practice.",
    price: 79,
    rating: 4.6,
    category: "Drinks",
    vendor: "Brew Block",
    availability: "Available",
    popularity: 80,
    prepTime: "6 min",
    image: "/food/mango-lassi.svg",
    accent: "from-orange-100 to-yellow-50",
  },
  {
    id: "keema-pao",
    name: "Spiced Keema Pao",
    description: "Slow-cooked keema with buttered pao, onions, and a squeeze of lime.",
    price: 169,
    rating: 4.7,
    category: "Non-Veg",
    vendor: "Central Grill Lab",
    availability: "Limited",
    popularity: 92,
    prepTime: "16 min",
    image: "/food/keema-pao.svg",
    accent: "from-rose-100 to-orange-50",
  },
];

export const mockUsers: MockUser[] = [
  {
    id: "student-01",
    name: "Aarav Singh",
    email: "aarav@centraluni.edu",
    role: "student",
  },
  {
    id: "vendor-01",
    name: "Mess Collective",
    email: "vendor@khanadoo.app",
    role: "vendor",
  },
  {
    id: "admin-01",
    name: "Campus Ops",
    email: "admin@khanadoo.app",
    role: "admin",
  },
];

export const mockOrders: Order[] = [
  {
    id: "KD-1024",
    userId: "student-01",
    vendor: "North Gate Kitchen",
    items: ["Masala Paneer Wrap", "Cold Coffee Float"],
    total: 228,
    status: "On the way",
    eta: "8 mins",
    placedAt: "Today, 1:05 PM",
  },
  {
    id: "KD-1019",
    userId: "student-01",
    vendor: "Mess Collective",
    items: ["Hostel Comfort Thali"],
    total: 149,
    status: "Delivered",
    eta: "Delivered",
    placedAt: "Yesterday, 8:10 PM",
  },
  {
    id: "KD-1007",
    userId: "student-01",
    vendor: "Library Lane Bites",
    items: ["Study Break Samosa Box", "Mango Lassi Cooler"],
    total: 168,
    status: "Delivered",
    eta: "Delivered",
    placedAt: "Friday, 4:30 PM",
  },
];

export const studentBenefits = [
  "Late-night friendly menus around hostels and library zones",
  "Quick reorder built for repeat campus cravings",
  "Transparent delivery ETA for student-heavy time slots",
];

export const platformStats = [
  { label: "Active students", value: "2,480" },
  { label: "Live vendors", value: "24" },
  { label: "Orders today", value: "612" },
  { label: "Avg. delivery", value: "14 min" },
];
